# `syslog` Source Example
# ------------------------------------------------------------------------------
# A simple example demonstrating the `syslog` source
# Docs: https://docs.vector.dev/usage/configuration/sources/syslog
#
# Note, that format described in RFC3164 is not supported
# In case, you are willing to apply Vector for collecting
# Nginx logs in syslog format, refer to the recipe in RFC3164 discussion:
# https://github.com/timberio/vector/issues/741
# (full version of it is here: https://chabik.com/2019/02/nginx-logging-to-syslog/)

[sources.my_syslog_source]
  # REQUIRED - General
  type = "syslog" # must be: syslog

  # OPTIONAL - General
  address = "0.0.0.0:9000" # no default
  max_length = 102400 # default, bytes
  mode = "tcp" # no default, enum: tcp, udp, unix
  path = "/path/to/socket" # no default

  # OPTIONAL - Context
  host_key = "host" # default
